In [1]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit([1, 2, 2, 6])

le.classes_

le.transform([1, 1, 2, 6]) 

le.inverse_transform([0, 0, 1, 2])

array([1, 1, 2, 6])

In [2]:
le.classes_

array([1, 2, 6])

In [4]:
import os

In [5]:
os.chdir('..')

In [6]:
from src.data import make_dataset
from src.features import build_features

In [8]:
df_bitcoin, df, df_test = make_dataset.get_preprocessed_datasets()

2019-11-03 17:01:44,212 - src.data.make_dataset - INFO - making final data sets from raw data
2019-11-03 17:01:44,509 - src.data.make_dataset - INFO - Shape of df_bitcoin: (2355, 2)
2019-11-03 17:01:44,511 - src.data.make_dataset - INFO - Shape of df: (4757, 91)

In [11]:
df.head()

,OBS_ID,ï..id,symbol,name,categories_0,contract_address,transaction_count,holder_count,timestamp,country_origin,...,KW31,KW32,KW33,KW34,KW35,KW36,KW37,KW38,KW39,success
0,235691,01coin,zoc,01coin,Masternodes,NaN,NaN,NaN,Sep-26-2019 15:59:01 PM,NaN,...,0.002447546274714919,0.002808322880574077,0.0021200694938956423,0.001355550652369834,0.002012671604248252,0.0023568770184417566,0.0025350649298760968,0.0021662825358147323,0.001778674696301052,0
1,235692,0x,zrx,0x,Protocol,0xe41d2489571d322189246dafa5ebde1f4699f498,975773.0,109840.0,Sep-26-2019 01:56:58 PM,US,...,0.21931512365670175,0.1902118244838738,0.1739528088194773,0.1768360401100923,0.1534983327381213,0.15961035385705513,0.16061107287163193,0.22629107696617964,0.21794407055321546,1
2,235693,0xcert,zxc,0xcert,Protocol,0x83e2be8d114f9661221384b3a50d24b96a5653f5,22730.0,13914.0,Sep-25-2019 11:58:48 PM,SI,...,0.0015627075063726896,0.0009794145108587154,0.0009140279072363044,0.001081632723442786,0.0009823537645584207,0.0009866124861903753,0.0006878811046944512,0.0009500823096029532,0.0007445952388706128,0
3,235694,0xdark,oxd,0xDark,NaN,0xe1ae07ea12bdae73b7f546075f5c78f65aad4876,125.0,51.0,Sep-26-2019 04:58:35 AM,NaN,...,0,0,0,0,0,0,0,0,0.04619907404199976,0
4,235695,10m-token,10mt,10M Token,NaN,0xe701cd3329057aea9d54300ddd05e41b8d74727a,16417.0,6250.0,Sep-25-2019 11:14:11 PM,NaN,...,0.0008870106032193045,0.0008870106032193045,0.0008870106032193045,0.0008870106032193045,0.0008870106032193045,0.0008870106032193045,0.0008870106032193045,0.0008870106032193045,0.0008870106032193045,0

In [12]:
fe = build_features.FeatureEngineering(df, df_bitcoin, df_test)

In [13]:
le = preprocessing.LabelEncoder()

In [16]:
df.categories_0.unique()

array(['Masternodes', 'Protocol', nan, 'Cryptocurrency',
       'Business Services', 'Sports', 'Infrastructure', 'Gambling',
       'Artificial Intelligence', 'Smart Contract Platform', 'Media',
       'Exchange-based Tokens', 'Decentralized Exchange', 'Education',
       'Finance / Banking', 'Entertainment', 'Real Estate', 'Other',
       'Tourism', 'Communication', 'Technology & Science',
       'Business Platform', 'Healthcare', 'Retail', 'Charity', 'Legal',
       'Manufacturing', 'Investment', 'Software', 'Privacy Coins',
       'Big Data', 'Virtual Reality', 'Asset-backed Tokens',
       'Stablecoins', 'Internet of Things (IOT)', 'Energy', 'Storage',
       'Augmented Reality', 'Index', 'Music'], dtype=object)

In [17]:
df.categories_0.isna().sum()

2609

In [22]:
df.loc[df.categories_0.isna(), 'categories_0'] = "NAN"

In [23]:
df.categories_0.isna().sum()

0

In [27]:
df.shape

(4757, 91)

In [28]:
df.assign(label_category = le.fit_transform(df.categories_0))

,OBS_ID,ï..id,symbol,name,categories_0,contract_address,transaction_count,holder_count,timestamp,country_origin,...,KW32,KW33,KW34,KW35,KW36,KW37,KW38,KW39,success,label_category
0,235691,01coin,zoc,01coin,Masternodes,NaN,NaN,NaN,Sep-26-2019 15:59:01 PM,NaN,...,0.002808322880574077,0.0021200694938956423,0.001355550652369834,0.002012671604248252,0.0023568770184417566,0.0025350649298760968,0.0021662825358147323,0.001778674696301052,0,23
1,235692,0x,zrx,0x,Protocol,0xe41d2489571d322189246dafa5ebde1f4699f498,975773.0,109840.0,Sep-26-2019 01:56:58 PM,US,...,0.1902118244838738,0.1739528088194773,0.1768360401100923,0.1534983327381213,0.15961035385705513,0.16061107287163193,0.22629107696617964,0.21794407055321546,1,29
2,235693,0xcert,zxc,0xcert,Protocol,0x83e2be8d114f9661221384b3a50d24b96a5653f5,22730.0,13914.0,Sep-25-2019 11:58:48 PM,SI,...,0.0009794145108587154,0.0009140279072363044,0.001081632723442786,0.0009823537645584207,0.0009866124861903753,0.0006878811046944512,0.0009500823096029532,0.0007445952388706128,0,29
3,235694,0xdark,oxd,0xDark,NAN,0xe1ae07ea12bdae73b7f546075f5c78f65aad4876,125.0,51.0,Sep-26-2019 04:58:35 AM,NaN,...,0,0,0,0,0,0,0,0.04619907404199976,0,26
4,235695,10m-token,10mt,10M Token,NAN,0xe701cd3329057aea9d54300ddd05e41b8d74727a,16417.0,6250.0,Sep-25-2019 11:14:11 PM,NaN,...,0.0008870106032193045,0.0008870106032193045,0.0008870106032193045,0.0008870106032193045,0.0008870106032193045,0.0008870106032193045,0.0008870106032193045,0.0008870106032193045,0,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4752,240443,zulu-republic-token,ztx,Zulu Republic Token,NAN,0xe8f9fa977ea585591d9f394681318c16552577fb,16776.0,4829.0,Sep-14-2019 05:37:47 PM,CH,...,0,0,0,0,0,0,0,0,0,26
4753,240444,zumy,zmy,Zumy,Internet of Things (IOT),NaN,NaN,NaN,NaN,GB,...,0.030020631293592375,0.0341321660015811,0.0304697181117438,0.020523623665310388,0.014533328424871593,0,0.017655037734807966,0.017458673754139658,0,19
4754,240445,zurcoin,zur,Zurcoin,NAN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0.00017877011071567577,8420000000,0,26
4755,240446,zuzubecoin,zube,zuzubecoin,NAN,0xc5e017450346e4f9a2e477519d65affcfc90586a,168.0,34.0,Sep-12-2019 06:14:33 PM,GB,...,90000000,"0,0000001",600000000,0,0,18000000000,"0,0000006",600000000,0,26
4756,240447,zxflea,xflea,zXFLEA,Masternodes,NaN,NaN,NaN,NaN,NaN,...,3400000000,3400000000,3400000000,3400000000,3400000000,3400000000,3400000000,3400000000,0,23